In [1]:
import numpy as np

In [3]:
a = np.array([[1,2,3],[4,5,6]])

In [4]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
print(a)

[[1 2 3]
 [4 5 6]]


In [6]:
a.ndim

2

In [8]:
b = np.array([[[1,2,3],[4,5,6]],[1,2,3]])

In [9]:
b

array([list([[1, 2, 3], [4, 5, 6]]), list([1, 2, 3])], dtype=object)

In [11]:
type(b)

numpy.ndarray

In [12]:
print(b)

[list([[1, 2, 3], [4, 5, 6]]) list([1, 2, 3])]


In [13]:
b.ndim

1

In [14]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
c = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [16]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
c.ndim

2

In [18]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
a.shape

(2, 3)

In [20]:
c.shape

(3, 3)

In [21]:
a.size

6

In [22]:
c.size

9

## reshape the array

In [23]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
a.shape

(2, 3)

In [25]:
a = a.reshape(3,2)

In [26]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [28]:
a.shape

(3, 2)

In [34]:
np.transpose(a)

array([[1, 3, 5],
       [2, 4, 6]])

In [35]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

## Slicing

In [36]:
a[0:][0:]

array([[1, 2],
       [3, 4],
       [5, 6]])

In [37]:
a[0:1][0:2]

array([[1, 2]])

In [38]:
a[0:-1][0:2]

array([[1, 2],
       [3, 4]])

In [39]:
a[1:2][0:]

array([[3, 4]])

## Other operations

In [40]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [41]:
a.max()

6

In [42]:
a.min()

1

In [43]:
a.sum()

21

In [44]:
a.sum(axis=0) # Column sum

array([ 9, 12])

In [46]:
a.sum(axis=1) # row sum

array([ 3,  7, 11])

In [47]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [48]:
np.std(a)

1.707825127659933

In [50]:
np.mean(a)

3.5

In [52]:
np.var(a)

2.9166666666666665

In [54]:
np.median(a)

3.5

In [57]:
np.sum(a)

21

## matrix multiplication

In [58]:
a = np.array([[2,3,4],[6,5,4]])

In [59]:
a

array([[2, 3, 4],
       [6, 5, 4]])

In [60]:
a.shape

(2, 3)

In [61]:
a.size

6

In [62]:
a.ndim

2

In [63]:
b = np.array([[1,2,3],[4,5,6],[1,1,1]])

In [64]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [1, 1, 1]])

In [65]:
b.shape

(3, 3)

In [66]:
b.size

9

In [67]:
b.ndim

2

In [68]:
np.dot(a,b)

array([[18, 23, 28],
       [30, 41, 52]])

In [69]:
c = np.array([[2,3,4],[6,5,4]])

In [70]:
d = np.array([[5,2,1],[4,6,9]])

In [72]:
np.vstack((c,d))

array([[2, 3, 4],
       [6, 5, 4],
       [5, 2, 1],
       [4, 6, 9]])

In [74]:
np.hstack((c,d))

array([[2, 3, 4, 5, 2, 1],
       [6, 5, 4, 4, 6, 9]])

In [75]:
a

array([[2, 3, 4],
       [6, 5, 4]])

In [76]:
np.ravel(a)

array([2, 3, 4, 6, 5, 4])

In [78]:
np.arange(4,50,3)

array([ 4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49])

In [80]:
np.arange(50,0,-5)

array([50, 45, 40, 35, 30, 25, 20, 15, 10,  5])

In [81]:
p = np.arange(5,51,5)

In [83]:
p.size

10

In [84]:
p.reshape(2,5)

array([[ 5, 10, 15, 20, 25],
       [30, 35, 40, 45, 50]])

In [85]:
p

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [86]:
p = p.reshape(5,2)

In [87]:
p

array([[ 5, 10],
       [15, 20],
       [25, 30],
       [35, 40],
       [45, 50]])