# Load Images using OpenCV

In [ ]:
import cv2

In [ ]:
# Colored Image
img = cv2.imread("img.jpg",1) # '1' use of color image

In [ ]:
# Black and White (Gray Scale)
img2 = cv2.imread("img.jpg",0) # '0' for gray scale

In [ ]:
print(img) # It gives 3-D array

In [ ]:
img.ndim

In [ ]:
print(img2)

In [ ]:
type(img)

In [ ]:
type(img2)

In [ ]:
print(img.shape) # '3' is no. of channels "RED,GREEN,BLUE"

In [ ]:
print(img2.shape)

# Displaying the image

In [2]:
import cv2
img = cv2.imread("img.jpg",0)

In [ ]:
cv2.imshow("IMAGE",img)
cv2.waitKey(5000) # Image displayed till 5 seconds, if argument set to 0 then image not disappear until we press and key.
cv2.destroyAllWindows()

# Resizing the image

In [ ]:
img = cv2.imread("img.jpg",0)

In [ ]:
img.shape

In [ ]:
resized_img = cv2.resize(img,(240,320))

In [ ]:
cv2.imshow("IMAGE",resized_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
# To get half size of image we can do:

In [ ]:
resized_img = cv2.resize(img,(int(img.shape[1]/2),int(img.shape[0]/2)))

In [ ]:
cv2.imshow("IMAGE",resized_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
img.shape

In [ ]:
img.shape[0]

# Face Detection Using OpenCV

In [3]:
# 1. Create a Cascade Classifier object (Cascade Classifier contain the feature of face)
face_cascade = cv2.CascadeClassifier("haarcascade_frontalface_default.xml")

In [4]:
# Reading the image as it is
img = cv2.imread("face.jpg")

In [5]:
# Reading the image as gray scale image
gray_img = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

In [6]:
# Search Coordinates of the image
faces = face_cascade.detectMultiScale(gray_img, scaleFactor = 1.05,minNeighbors=5)

In [7]:
print(type(faces))

<class 'numpy.ndarray'>


In [8]:
print(faces)

[[ 457  733  915  915]
 [1007 1856   57   57]
 [1016 1947   49   49]]


In [14]:
for x,y,w,h in faces:
    img = cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,0),3)

In [15]:
resized = cv2.resize(img, (int(img.shape[1]/7),int(img.shape[0]/7)))

In [16]:
cv2.imshow("Gray", resized)
 
cv2.waitKey(0)
 
cv2.destroyAllWindows()

# Capturing Video

In [17]:
# We will be using loops to build a window where images will appear 
# really fast, so that you can see it as a video.

In [18]:
import cv2

In [19]:
video = cv2.VideoCapture(0)
video.release()

In [20]:
import cv2,time

In [21]:
video = cv2.VideoCapture(0)
time.sleep(3)
video.release()

In [23]:
import cv2,time

In [24]:
video = cv2.VideoCapture(0)

In [25]:
check,frame = video.read()

In [26]:
print(frame)

[[[197 141  89]
  [195 138  87]
  [202 147 100]
  ...
  [216 171 141]
  [222 175 150]
  [230 184 158]]

 [[201 147  95]
  [202 148  96]
  [201 148 101]
  ...
  [216 171 141]
  [217 171 144]
  [219 172 145]]

 [[210 160 109]
  [211 161 111]
  [208 158 108]
  ...
  [217 172 142]
  [214 170 142]
  [215 172 144]]

 ...

 [[ 56  37  41]
  [ 60  41  45]
  [ 61  42  46]
  ...
  [118  87  62]
  [116  86  61]
  [115  84  60]]

 [[ 56  37  41]
  [ 61  42  46]
  [ 62  43  47]
  ...
  [116  86  64]
  [114  86  61]
  [116  87  62]]

 [[ 53  33  40]
  [ 55  36  42]
  [ 60  40  47]
  ...
  [110  81  58]
  [108  81  58]
  [110  83  61]]]


In [27]:
time.sleep(3)

In [28]:
video.release()

In [1]:
# Code 
import cv2,time

In [2]:
video = cv2.VideoCapture(0)

In [3]:
check,frame = video.read()

In [4]:
print(check)

True


In [5]:
print(frame)

[[[115 104  93]
  [119 107  97]
  [119 110  97]
  ...
  [124 129 136]
  [130 134 145]
  [143 147 158]]

 [[113 104  93]
  [119 110  99]
  [116 109  96]
  ...
  [124 130 134]
  [126 131 140]
  [135 139 148]]

 [[124 117 106]
  [128 122 111]
  [113 109  98]
  ...
  [126 132 136]
  [126 132 138]
  [129 134 140]]

 ...

 [[ 65  67  97]
  [ 65  67  97]
  [ 63  67  97]
  ...
  [127 133 130]
  [127 133 130]
  [126 131 129]]

 [[ 65  67  97]
  [ 65  67  97]
  [ 64  66  95]
  ...
  [124 126 124]
  [124 126 126]
  [125 127 127]]

 [[ 72  75 102]
  [ 67  70  97]
  [ 65  67  97]
  ...
  [129 130 127]
  [124 126 124]
  [124 126 124]]]


In [6]:
frame.ndim

3

In [7]:
time.sleep(3)

In [8]:
video.release()

In [1]:
# Final
import cv2,time
video = cv2.VideoCapture(0)
check,frame = video.read()
time.sleep(3)
cv2.imshow("Capturing",frame)
cv2.waitKey(0)
video.release()
cv2.destroyAllWindows()

In [1]:
# Capturing the complete video

In [2]:
# we have to use while loop

In [4]:
import cv2,time
video = cv2.VideoCapture(0)
a = 1

In [1]:
import cv2,time
video = cv2.VideoCapture(0)
a = 1

while True:
    a = a + 1
    check,frame=video.read()
    print(frame)
    gray = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    cv2.imshow('Capturing',gray)
    key=cv2.waitKey(1)
    if key==ord('q'):
        break

print(a)
video.release()
cv2.destroyAllWindows

[[[  6   4   0]
  [  7   5   1]
  [  6   4   0]
  ...
  [ 16  11   2]
  [ 22  11   0]
  [ 23  12   0]]

 [[  7   5   1]
  [  8   7   2]
  [  8   7   2]
  ...
  [ 15  12   3]
  [ 19  12   1]
  [ 20  13   3]]

 [[  9   8   3]
  [ 11  10   6]
  [ 10   9   5]
  ...
  [ 16  13   6]
  [ 20  13   4]
  [ 22  15   7]]

 ...

 [[109 114 134]
  [111 116 136]
  [136 141 159]
  ...
  [122 122 111]
  [123 124 110]
  [126 126 113]]

 [[106 113 131]
  [104 111 128]
  [141 146 163]
  ...
  [119 121 110]
  [122 125 111]
  [125 128 114]]

 [[127 134 153]
  [113 120 139]
  [148 148 170]
  ...
  [117 124 114]
  [120 128 116]
  [121 129 117]]]
[[[141 146 134]
  [128 133 121]
  [141 149 135]
  ...
  [199 216 214]
  [202 215 214]
  [204 218 217]]

 [[146 151 139]
  [139 144 132]
  [154 160 143]
  ...
  [198 214 215]
  [199 215 216]
  [204 220 221]]

 [[161 163 152]
  [158 161 149]
  [155 159 142]
  ...
  [200 214 215]
  [200 214 215]
  [202 215 216]]

 ...

 [[ 44  48  68]
  [ 65  69  89]
  [ 68  71  98]
  ..

[[[153 154 129]
  [150 151 126]
  [165 166 141]
  ...
  [199 215 216]
  [198 214 215]
  [199 215 216]]

 [[154 155 132]
  [153 154 131]
  [149 150 125]
  ...
  [199 215 216]
  [199 215 218]
  [201 216 219]]

 [[160 160 140]
  [150 150 129]
  [144 142 121]
  ...
  [197 215 216]
  [192 208 211]
  [189 204 207]]

 ...

 [[ 63  67  82]
  [ 84  88 103]
  [ 79  81 101]
  ...
  [ 72  74  67]
  [ 73  75  68]
  [ 75  76  69]]

 [[ 63  64  80]
  [ 78  79  95]
  [ 73  73  91]
  ...
  [ 69  70  63]
  [ 72  74  67]
  [ 71  73  66]]

 [[ 70  74  88]
  [ 82  86  99]
  [ 80  74  91]
  ...
  [ 67  67  60]
  [ 72  74  67]
  [ 70  71  64]]]
[[[120 116  94]
  [152 148 125]
  [159 161 143]
  ...
  [200 216 224]
  [201 215 223]
  [201 215 223]]

 [[141 139 121]
  [160 157 139]
  [158 160 142]
  ...
  [199 213 223]
  [201 215 223]
  [201 215 223]]

 [[153 150 132]
  [174 171 153]
  [168 168 150]
  ...
  [198 212 220]
  [197 212 217]
  [198 213 218]]

 ...

 [[ 68  75  86]
  [ 67  74  85]
  [ 63  63  93]
  ..

[[[143 151 128]
  [142 150 126]
  [147 156 137]
  ...
  [189 206 213]
  [203 220 225]
  [201 218 223]]

 [[149 154 133]
  [155 160 139]
  [148 157 138]
  ...
  [194 211 216]
  [207 224 229]
  [205 222 228]]

 [[161 165 144]
  [168 172 151]
  [145 156 137]
  ...
  [200 217 222]
  [200 217 222]
  [201 218 223]]

 ...

 [[ 73  75  93]
  [ 60  63  81]
  [ 98 104 126]
  ...
  [ 69  73  66]
  [ 64  68  61]
  [ 69  73  66]]

 [[ 75  76  92]
  [ 62  63  79]
  [123 126 143]
  ...
  [ 68  72  64]
  [ 65  69  62]
  [ 65  69  62]]

 [[ 74  75  89]
  [ 68  69  83]
  [139 138 150]
  ...
  [ 69  75  68]
  [ 64  68  61]
  [ 64  68  61]]]
[[[156 151 133]
  [142 137 120]
  [151 148 130]
  ...
  [207 219 227]
  [216 229 239]
  [205 219 229]]

 [[159 156 138]
  [152 149 131]
  [152 149 131]
  ...
  [212 224 232]
  [197 211 219]
  [203 217 225]]

 [[170 170 149]
  [165 165 144]
  [162 160 140]
  ...
  [205 222 228]
  [200 216 224]
  [200 216 224]]

 ...

 [[ 64  71  91]
  [ 90  96 116]
  [187 192 210]
  ..

[[[143 137 115]
  [144 138 116]
  [156 148 133]
  ...
  [196 213 218]
  [197 214 220]
  [203 220 225]]

 [[139 134 114]
  [135 131 111]
  [140 135 117]
  ...
  [197 214 221]
  [199 214 220]
  [201 215 221]]

 [[152 150 129]
  [143 140 120]
  [143 140 120]
  ...
  [197 214 221]
  [199 214 220]
  [199 214 220]]

 ...

 [[ 61  53  37]
  [ 59  52  36]
  [ 56  51  35]
  ...
  [ 69  71  60]
  [ 71  74  62]
  [ 75  77  66]]

 [[ 63  56  38]
  [ 62  54  37]
  [ 57  52  35]
  ...
  [ 67  71  61]
  [ 71  73  64]
  [ 72  74  65]]

 [[ 68  61  41]
  [ 64  57  37]
  [ 63  58  40]
  ...
  [ 69  73  64]
  [ 70  74  65]
  [ 70  74  65]]]
[[[148 151 128]
  [129 132 109]
  [149 153 125]
  ...
  [199 214 220]
  [198 215 223]
  [200 216 224]]

 [[158 164 140]
  [155 160 137]
  [163 169 141]
  ...
  [196 213 218]
  [196 213 220]
  [196 213 220]]

 [[162 167 144]
  [177 182 159]
  [172 179 151]
  ...
  [191 208 216]
  [189 208 216]
  [192 210 218]]

 ...

 [[ 53  49  36]
  [ 42  39  25]
  [ 54  53  39]
  ..

[[[147 148 127]
  [157 157 136]
  [157 157 136]
  ...
  [195 220 227]
  [196 220 224]
  [193 217 222]]

 [[149 149 128]
  [153 153 133]
  [153 156 135]
  ...
  [197 218 225]
  [188 210 215]
  [191 212 217]]

 [[172 172 151]
  [154 155 134]
  [153 153 133]
  ...
  [195 217 224]
  [192 214 218]
  [188 210 215]]

 ...

 [[ 52  43  39]
  [ 62  54  50]
  [ 64  57  50]
  ...
  [ 68  70  60]
  [ 68  70  60]
  [ 70  72  63]]

 [[ 61  54  55]
  [ 62  55  56]
  [ 61  57  55]
  ...
  [ 69  71  61]
  [ 71  73  64]
  [ 73  75  66]]

 [[ 60  52  55]
  [ 62  55  58]
  [ 62  58  58]
  ...
  [ 73  75  66]
  [ 76  78  68]
  [ 76  78  68]]]
[[[144 143 125]
  [140 140 122]
  [147 151 131]
  ...
  [191 213 214]
  [195 214 220]
  [199 218 223]]

 [[139 139 119]
  [142 142 121]
  [148 151 128]
  ...
  [191 213 215]
  [193 212 217]
  [198 217 222]]

 [[164 164 143]
  [156 156 135]
  [153 154 131]
  ...
  [190 212 214]
  [186 205 210]
  [182 202 207]]

 ...

 [[ 66  64  51]
  [ 60  59  45]
  [ 62  61  47]
  ..

[[[148 148 120]
  [152 151 124]
  [152 154 126]
  ...
  [199 215 218]
  [201 216 219]
  [203 218 221]]

 [[149 150 123]
  [157 158 131]
  [149 153 125]
  ...
  [202 217 220]
  [204 219 222]
  [204 219 222]]

 [[179 181 153]
  [182 184 157]
  [154 161 130]
  ...
  [209 223 229]
  [205 220 225]
  [203 218 223]]

 ...

 [[ 76  72  50]
  [ 69  65  43]
  [ 66  63  45]
  ...
  [ 69  70  63]
  [ 70  72  63]
  [ 71  73  64]]

 [[ 72  65  46]
  [ 71  64  44]
  [ 67  64  48]
  ...
  [ 68  70  60]
  [ 71  73  64]
  [ 72  74  65]]

 [[ 70  63  45]
  [ 70  63  45]
  [ 65  60  44]
  ...
  [ 75  79  70]
  [ 74  78  68]
  [ 74  78  68]]]
[[[148 150 129]
  [143 145 125]
  [149 153 135]
  ...
  [191 209 210]
  [205 221 222]
  [205 221 222]]

 [[148 149 131]
  [147 148 130]
  [147 153 135]
  ...
  [194 211 214]
  [198 215 221]
  [202 219 224]]

 [[155 156 138]
  [159 161 143]
  [153 157 138]
  ...
  [188 205 210]
  [198 215 221]
  [198 215 221]]

 ...

 [[ 70  66  46]
  [ 67  62  42]
  [ 61  56  36]
  ..

[[[151 153 123]
  [153 155 126]
  [155 155 126]
  ...
  [198 217 222]
  [200 219 226]
  [202 221 228]]

 [[153 154 129]
  [163 164 139]
  [158 158 126]
  ...
  [205 224 229]
  [199 217 225]
  [200 219 226]]

 [[160 161 136]
  [178 179 154]
  [167 170 138]
  ...
  [200 219 224]
  [199 217 225]
  [199 217 225]]

 ...

 [[ 63  70  88]
  [ 64  71  89]
  [ 80  89 111]
  ...
  [ 69  71  60]
  [ 71  71  61]
  [ 77  76  67]]

 [[ 57  63  85]
  [ 67  74  96]
  [100 107 136]
  ...
  [ 57  59  50]
  [ 66  66  57]
  [ 70  69  60]]

 [[ 57  62  89]
  [ 70  75 102]
  [114 117 155]
  ...
  [ 45  47  38]
  [ 63  62  53]
  [ 65  65  56]]]
[[[155 156 138]
  [155 156 138]
  [154 156 130]
  ...
  [197 209 215]
  [196 208 214]
  [210 222 228]]

 [[159 159 139]
  [163 163 142]
  [157 157 135]
  ...
  [206 218 226]
  [218 233 236]
  [206 222 225]]

 [[162 165 140]
  [169 172 147]
  [163 163 140]
  ...
  [201 215 221]
  [201 218 221]
  [194 211 214]]

 ...

 [[ 70  73  93]
  [ 62  64  85]
  [ 82  83 108]
  ..

[[[145 147 118]
  [140 143 113]
  [163 162 139]
  ...
  [195 209 217]
  [195 209 217]
  [195 209 217]]

 [[147 149 122]
  [151 153 125]
  [154 156 130]
  ...
  [197 214 220]
  [197 211 219]
  [197 211 219]]

 [[156 157 132]
  [156 157 132]
  [154 156 130]
  ...
  [201 218 223]
  [200 216 224]
  [201 217 225]]

 ...

 [[ 84  81 102]
  [ 77  74  95]
  [ 88  88 106]
  ...
  [ 69  73  64]
  [ 71  76  66]
  [ 70  74  65]]

 [[ 79  76 101]
  [ 74  70  95]
  [106 101 122]
  ...
  [ 69  73  64]
  [ 71  76  66]
  [ 70  74  65]]

 [[ 75  66 101]
  [ 72  64  99]
  [120 111 137]
  ...
  [ 72  74  65]
  [ 71  76  66]
  [ 70  74  65]]]
[[[146 146 116]
  [144 144 114]
  [155 155 126]
  ...
  [196 216 209]
  [197 214 210]
  [197 214 210]]

 [[147 150 120]
  [151 153 123]
  [163 165 135]
  ...
  [197 216 214]
  [196 214 215]
  [201 219 219]]

 [[172 174 144]
  [168 171 141]
  [168 171 141]
  ...
  [197 215 216]
  [197 215 218]
  [201 218 221]]

 ...

 [[ 74  74  94]
  [ 77  77  98]
  [ 89  88 111]
  ..

  [ 67  72  58]]]
[[[139 148 127]
  [146 155 134]
  [150 157 138]
  ...
  [189 205 206]
  [211 227 228]
  [204 220 221]]

 [[144 149 128]
  [153 157 136]
  [151 156 137]
  ...
  [190 205 210]
  [202 217 220]
  [210 225 228]]

 [[155 160 139]
  [161 165 144]
  [156 161 140]
  ...
  [191 208 214]
  [200 217 220]
  [209 226 229]]

 ...

 [[ 63  72  92]
  [ 61  70  89]
  [101 111 128]
  ...
  [ 70  74  65]
  [ 70  74  65]
  [ 69  73  64]]

 [[ 68  77  95]
  [ 63  73  90]
  [130 138 155]
  ...
  [ 70  74  65]
  [ 68  72  63]
  [ 65  70  60]]

 [[ 78  85 103]
  [ 67  75  92]
  [165 170 188]
  ...
  [ 65  69  62]
  [ 62  66  59]
  [ 55  59  52]]]
[[[133 126 104]
  [151 145 123]
  [167 154 130]
  ...
  [200 221 230]
  [201 221 233]
  [200 220 232]]

 [[161 160 135]
  [159 158 133]
  [160 156 132]
  ...
  [200 221 230]
  [199 219 231]
  [199 219 231]]

 [[174 173 148]
  [172 171 146]
  [170 167 142]
  ...
  [198 218 228]
  [195 216 225]
  [194 215 224]]

 ...

 [[ 67  70  97]
  [ 71  74 101]
  

[[[142 142 121]
  [126 127 106]
  [169 174 162]
  ...
  [199 222 231]
  [201 222 231]
  [198 218 228]]

 [[135 137 117]
  [131 134 113]
  [171 175 159]
  ...
  [198 221 228]
  [200 221 230]
  [199 219 229]]

 [[142 146 128]
  [155 159 140]
  [158 163 144]
  ...
  [200 219 226]
  [199 217 225]
  [198 216 224]]

 ...

 [[ 64  70  83]
  [ 67  73  86]
  [ 77  83  94]
  ...
  [ 62  65  60]
  [ 62  66  59]
  [ 63  67  60]]

 [[ 57  65  78]
  [ 63  71  84]
  [ 74  81  92]
  ...
  [ 63  69  64]
  [ 63  69  64]
  [ 61  67  62]]

 [[ 45  54  67]
  [ 58  67  79]
  [ 71  77  88]
  ...
  [ 63  71  68]
  [ 69  75  70]
  [ 63  69  64]]]
[[[143 139 109]
  [165 161 131]
  [160 164 139]
  ...
  [203 214 223]
  [202 213 221]
  [202 213 221]]

 [[143 142 115]
  [163 163 136]
  [160 163 140]
  ...
  [202 216 224]
  [197 211 219]
  [201 215 223]]

 [[159 160 137]
  [166 167 144]
  [162 165 142]
  ...
  [202 218 226]
  [196 212 222]
  [196 212 222]]

 ...

 [[ 68  72  85]
  [ 77  81  95]
  [ 77  84 103]
  ..

[[[142 145 133]
  [139 141 130]
  [153 154 142]
  ...
  [198 215 221]
  [203 218 223]
  [203 218 223]]

 [[144 148 134]
  [146 149 135]
  [150 153 139]
  ...
  [197 214 221]
  [198 215 221]
  [207 224 229]]

 [[160 163 149]
  [163 166 152]
  [156 158 139]
  ...
  [196 215 223]
  [195 214 220]
  [194 213 218]]

 ...

 [[ 56  50  37]
  [ 59  52  39]
  [ 60  53  40]
  ...
  [ 76  78  67]
  [ 75  80  68]
  [ 75  80  68]]

 [[ 54  50  39]
  [ 55  51  40]
  [ 57  51  40]
  ...
  [ 73  76  64]
  [ 75  80  68]
  [ 75  80  68]]

 [[ 56  52  41]
  [ 55  51  40]
  [ 56  49  39]
  ...
  [ 68  70  59]
  [ 75  80  68]
  [ 77  82  70]]]
[[[154 150 118]
  [155 151 119]
  [163 164 132]
  ...
  [199 213 223]
  [198 212 222]
  [203 216 227]]

 [[153 150 121]
  [154 152 122]
  [153 153 123]
  ...
  [194 210 220]
  [184 200 210]
  [200 216 225]]

 [[166 165 140]
  [157 155 130]
  [154 153 128]
  ...
  [198 214 224]
  [196 212 222]
  [198 214 224]]

 ...

 [[ 52  50  39]
  [ 50  48  36]
  [ 52  50  37]
  ..

[[[136 139 114]
  [149 152 127]
  [150 154 126]
  ...
  [196 215 213]
  [196 213 218]
  [214 231 236]]

 [[145 149 123]
  [156 159 134]
  [148 151 126]
  ...
  [198 216 217]
  [196 214 217]
  [207 224 227]]

 [[169 174 151]
  [178 183 160]
  [157 160 137]
  ...
  [200 218 218]
  [200 217 220]
  [205 223 226]]

 ...

 [[ 52  49  40]
  [ 52  49  40]
  [ 53  51  42]
  ...
  [ 69  73  64]
  [ 71  76  66]
  [ 75  79  70]]

 [[ 53  51  42]
  [ 55  53  44]
  [ 55  53  44]
  ...
  [ 67  71  61]
  [ 70  74  67]
  [ 76  80  73]]

 [[ 54  49  40]
  [ 63  58  50]
  [ 58  55  46]
  ...
  [ 63  69  64]
  [ 68  74  67]
  [ 75  81  74]]]
[[[138 142 105]
  [144 148 111]
  [153 153 122]
  ...
  [197 213 223]
  [197 213 223]
  [193 209 218]]

 [[149 151 119]
  [153 156 124]
  [154 157 125]
  ...
  [193 211 221]
  [199 217 227]
  [207 225 235]]

 [[169 173 145]
  [173 177 150]
  [167 171 144]
  ...
  [187 205 215]
  [198 216 225]
  [202 220 230]]

 ...

 [[ 56  55  48]
  [ 62  61  54]
  [ 52  51  45]
  ..

[[[139 139 121]
  [140 140 122]
  [145 145 127]
  ...
  [196 213 218]
  [200 216 225]
  [207 222 232]]

 [[150 150 129]
  [153 153 133]
  [151 150 132]
  ...
  [195 211 219]
  [196 215 224]
  [201 219 229]]

 [[172 174 154]
  [176 178 157]
  [170 170 149]
  ...
  [193 212 219]
  [196 215 223]
  [201 220 227]]

 ...

 [[ 55  64  74]
  [ 62  71  81]
  [ 56  65  75]
  ...
  [ 64  66  57]
  [ 68  70  60]
  [ 73  75  66]]

 [[ 55  63  76]
  [ 48  56  69]
  [ 43  51  64]
  ...
  [ 65  67  58]
  [ 66  68  59]
  [ 72  74  65]]

 [[ 52  61  74]
  [ 50  58  71]
  [ 48  56  69]
  ...
  [ 63  64  57]
  [ 62  65  60]
  [ 64  68  63]]]
[[[145 153 125]
  [136 145 117]
  [148 153 132]
  ...
  [189 211 207]
  [186 204 203]
  [218 237 235]]

 [[145 153 125]
  [136 145 117]
  [147 155 129]
  ...
  [194 212 212]
  [198 218 218]
  [210 231 231]]

 [[158 162 136]
  [169 172 147]
  [166 170 144]
  ...
  [203 221 224]
  [200 219 224]
  [200 219 224]]

 ...

 [[ 55  59  72]
  [ 53  57  70]
  [ 51  56  72]
  ..

[[[138 138 106]
  [153 153 122]
  [155 155 127]
  ...
  [203 217 214]
  [203 217 214]
  [206 221 217]]

 [[152 151 124]
  [154 154 126]
  [155 154 129]
  ...
  [204 220 219]
  [202 219 215]
  [204 221 217]]

 [[156 157 132]
  [154 156 130]
  [154 152 130]
  ...
  [202 221 219]
  [200 218 217]
  [201 219 218]]

 ...

 [[ 52  53  39]
  [ 52  53  39]
  [ 48  48  35]
  ...
  [ 73  79  71]
  [ 73  79  71]
  [ 71  78  70]]

 [[ 49  49  36]
  [ 49  49  36]
  [ 48  48  35]
  ...
  [ 76  80  73]
  [ 71  78  70]
  [ 63  70  62]]

 [[ 46  47  35]
  [ 48  48  36]
  [ 49  49  38]
  ...
  [ 67  70  65]
  [ 67  70  63]
  [ 63  67  60]]]
[[[135 133 102]
  [147 145 113]
  [161 156 127]
  ...
  [199 219 219]
  [198 218 218]
  [196 217 217]]

 [[147 152 119]
  [148 153 120]
  [152 157 127]
  ...
  [199 218 221]
  [198 217 220]
  [196 216 219]]

 [[165 167 137]
  [159 161 131]
  [155 159 129]
  ...
  [201 221 224]
  [198 217 220]
  [189 209 212]]

 ...

 [[ 50  47  40]
  [ 51  48  41]
  [ 48  47  40]
  ..

[[[155 151 129]
  [153 149 126]
  [159 155 130]
  ...
  [205 217 223]
  [202 216 222]
  [199 214 220]]

 [[162 158 138]
  [141 137 117]
  [155 151 129]
  ...
  [204 219 224]
  [200 217 222]
  [208 225 230]]

 [[162 158 136]
  [148 144 122]
  [153 151 129]
  ...
  [198 212 220]
  [195 211 219]
  [194 210 218]]

 ...

 [[ 51  49  38]
  [ 50  48  36]
  [ 50  48  36]
  ...
  [ 70  74  65]
  [ 70  74  65]
  [ 72  77  67]]

 [[ 46  47  35]
  [ 46  47  35]
  [ 50  48  36]
  ...
  [ 60  64  54]
  [ 67  71  61]
  [ 71  76  66]]

 [[ 54  49  40]
  [ 54  49  40]
  [ 53  48  39]
  ...
  [ 61  65  56]
  [ 67  71  61]
  [ 70  74  65]]]
[[[146 144 122]
  [146 144 122]
  [164 160 140]
  ...
  [193 209 217]
  [189 206 213]
  [200 216 224]]

 [[143 146 123]
  [147 149 126]
  [154 155 132]
  ...
  [195 211 219]
  [197 214 220]
  [200 217 222]]

 [[163 166 141]
  [164 167 142]
  [153 157 132]
  ...
  [201 218 223]
  [201 218 223]
  [201 218 223]]

 ...

 [[ 59  61  43]
  [ 55  56  38]
  [ 53  55  37]
  ..

[[[134 140 124]
  [111 117 100]
  [175 179 181]
  ...
  [195 214 220]
  [193 212 217]
  [196 216 221]]

 [[146 150 131]
  [132 136 117]
  [153 157 149]
  ...
  [196 216 221]
  [192 211 216]
  [194 213 218]]

 [[163 167 149]
  [158 163 144]
  [154 158 139]
  ...
  [200 217 222]
  [196 213 218]
  [196 213 218]]

 ...

 [[ 52  57  75]
  [ 56  61  78]
  [ 58  63  81]
  ...
  [ 73  75  66]
  [ 70  72  63]
  [ 69  71  61]]

 [[ 70  75  92]
  [ 59  64  82]
  [ 58  63  81]
  ...
  [ 65  67  58]
  [ 66  68  59]
  [ 65  67  58]]

 [[ 63  70  88]
  [ 57  64  82]
  [ 55  62  78]
  ...
  [ 56  58  49]
  [ 66  68  59]
  [ 64  66  57]]]
[[[146 154 128]
  [146 154 128]
  [149 155 129]
  ...
  [201 221 222]
  [201 219 219]
  [200 218 218]]

 [[150 156 130]
  [153 158 133]
  [151 155 127]
  ...
  [198 217 222]
  [198 217 222]
  [198 217 222]]

 [[159 163 136]
  [158 162 134]
  [155 159 129]
  ...
  [199 218 223]
  [202 221 228]
  [202 221 228]]

 ...

 [[ 53  58  67]
  [ 51  55  64]
  [ 59  61  72]
  ..

[[[121 131 110]
  [138 147 126]
  [147 158 132]
  ...
  [184 201 207]
  [187 204 209]
  [216 233 238]]

 [[137 149 127]
  [147 159 138]
  [145 157 133]
  ...
  [196 215 224]
  [200 219 226]
  [215 234 241]]

 [[149 159 138]
  [159 168 147]
  [153 165 142]
  ...
  [199 220 227]
  [198 219 226]
  [199 220 227]]

 ...

 [[ 55  53  42]
  [ 59  57  46]
  [ 63  63  50]
  ...
  [ 85  86  81]
  [ 77  80  76]
  [ 75  78  73]]

 [[ 55  54  45]
  [ 53  53  44]
  [ 52  52  41]
  ...
  [ 70  71  66]
  [ 72  76  71]
  [ 74  77  72]]

 [[ 56  56  45]
  [ 53  54  42]
  [ 48  51  37]
  ...
  [ 76  77  72]
  [ 71  75  70]
  [ 72  76  71]]]
[[[145 142 115]
  [157 154 127]
  [159 159 127]
  ...
  [198 215 221]
  [196 213 220]
  [195 211 219]]

 [[148 147 124]
  [157 155 132]
  [158 157 132]
  ...
  [201 217 225]
  [198 215 223]
  [197 214 221]]

 [[165 162 142]
  [162 160 140]
  [159 160 137]
  ...
  [202 218 226]
  [200 216 225]
  [200 216 225]]

 ...

 [[ 52  54  37]
  [ 50  51  35]
  [ 46  48  32]
  ..

[[[144 147 124]
  [147 149 126]
  [155 154 129]
  ...
  [192 213 211]
  [194 214 215]
  [201 221 222]]

 [[147 149 126]
  [151 154 131]
  [154 156 130]
  ...
  [193 213 214]
  [192 212 212]
  [198 218 218]]

 [[159 162 139]
  [170 173 150]
  [160 164 139]
  ...
  [192 214 217]
  [192 214 217]
  [193 215 218]]

 ...

 [[ 49  51  62]
  [ 54  56  67]
  [ 53  55  66]
  ...
  [ 76  78  68]
  [ 75  77  67]
  [ 73  75  66]]

 [[ 57  59  71]
  [ 64  66  78]
  [ 56  58  69]
  ...
  [ 69  74  62]
  [ 70  75  63]
  [ 69  74  62]]

 [[ 63  63  72]
  [ 75  75  84]
  [ 66  68  79]
  ...
  [ 67  72  60]
  [ 68  72  63]
  [ 68  72  63]]]
[[[136 142 116]
  [143 149 123]
  [151 158 130]
  ...
  [190 208 209]
  [188 206 207]
  [186 204 204]]

 [[149 151 131]
  [152 155 134]
  [156 158 138]
  ...
  [192 212 212]
  [200 218 218]
  [197 215 216]]

 [[165 168 145]
  [164 167 144]
  [160 163 140]
  ...
  [196 216 219]
  [200 218 218]
  [198 216 217]]

 ...

 [[ 51  60  71]
  [ 49  58  68]
  [ 50  59  69]
  ..

[[[148 149 131]
  [150 152 133]
  [156 156 146]
  ...
  [199 218 221]
  [201 221 222]
  [202 222 223]]

 [[148 149 131]
  [151 153 135]
  [153 155 139]
  ...
  [200 219 224]
  [199 218 223]
  [201 220 225]]

 [[160 160 140]
  [157 157 136]
  [156 156 135]
  ...
  [198 219 224]
  [199 218 223]
  [196 216 221]]

 ...

 [[250 253 255]
  [251 254 255]
  [251 255 255]
  ...
  [ 68  72  64]
  [ 70  74  67]
  [ 72  76  69]]

 [[251 254 255]
  [251 254 255]
  [251 255 255]
  ...
  [ 65  69  62]
  [ 70  74  67]
  [ 71  75  68]]

 [[251 254 255]
  [251 254 255]
  [251 255 255]
  ...
  [ 69  71  61]
  [ 72  74  67]
  [ 72  74  67]]]
[[[144 148 122]
  [144 148 122]
  [148 154 128]
  ...
  [201 216 228]
  [201 216 228]
  [205 221 233]]

 [[149 150 125]
  [150 151 126]
  [149 152 127]
  ...
  [200 216 224]
  [202 218 226]
  [204 221 228]]

 [[167 168 143]
  [158 159 134]
  [154 156 130]
  ...
  [201 217 225]
  [202 218 228]
  [203 219 229]]

 ...

 [[247 254 255]
  [247 254 255]
  [249 255 255]
  ..

  [ 67  71  61]]]
[[[135 149 116]
  [125 140 106]
  [139 151 118]
  ...
  [200 218 228]
  [199 218 221]
  [196 216 219]]

 [[138 152 121]
  [138 152 121]
  [140 154 123]
  ...
  [199 217 225]
  [196 216 221]
  [195 214 220]]

 [[155 166 138]
  [154 165 137]
  [145 156 127]
  ...
  [198 216 224]
  [196 215 223]
  [194 213 220]]

 ...

 [[ 97  99  88]
  [ 85  88  76]
  [ 80  83  62]
  ...
  [ 69  73  66]
  [ 68  72  64]
  [ 70  74  67]]

 [[ 95  94  80]
  [ 80  78  65]
  [ 74  75  52]
  ...
  [ 71  75  68]
  [ 67  73  66]
  [ 67  73  66]]

 [[ 86  85  69]
  [ 79  78  62]
  [ 66  66  46]
  ...
  [ 74  77  72]
  [ 68  73  70]
  [ 68  73  70]]]
[[[152 152 133]
  [152 152 133]
  [152 149 131]
  ...
  [199 213 223]
  [199 213 223]
  [203 216 227]]

 [[156 156 135]
  [156 156 135]
  [157 157 136]
  ...
  [201 214 224]
  [201 214 224]
  [203 216 227]]

 [[155 158 133]
  [155 158 133]
  [156 159 134]
  ...
  [211 225 233]
  [202 216 224]
  [202 216 224]]

 ...

 [[ 72  72  50]
  [ 71  71  48]
  

  [ 73  78  73]]]
[[[152 150 128]
  [146 144 122]
  [147 145 115]
  ...
  [194 215 213]
  [193 213 214]
  [195 215 216]]

 [[156 156 133]
  [149 149 126]
  [151 152 127]
  ...
  [182 200 201]
  [184 202 203]
  [197 215 216]]

 [[165 168 145]
  [159 162 139]
  [164 167 142]
  ...
  [188 205 208]
  [194 211 214]
  [198 216 219]]

 ...

 [[ 53  50  34]
  [ 58  54  39]
  [ 74  71  55]
  ...
  [ 72  77  67]
  [ 71  76  66]
  [ 71  76  66]]

 [[ 62  62  44]
  [ 67  67  49]
  [ 67  67  49]
  ...
  [ 67  74  64]
  [ 67  74  64]
  [ 66  72  63]]

 [[ 64  63  45]
  [ 64  63  45]
  [ 66  65  47]
  ...
  [ 66  72  63]
  [ 66  72  63]
  [ 66  72  63]]]
[[[139 139 121]
  [158 157 139]
  [159 159 140]
  ...
  [195 212 215]
  [202 217 220]
  [204 219 222]]

 [[153 153 133]
  [161 161 141]
  [157 159 139]
  ...
  [190 207 213]
  [197 214 220]
  [202 219 224]]

 [[165 165 143]
  [171 171 148]
  [158 161 140]
  ...
  [190 207 213]
  [196 213 218]
  [200 217 222]]

 ...

 [[ 68  62  49]
  [ 70  64  51]
  

[[[140 138 106]
  [134 132 101]
  [166 169 135]
  ...
  [198 212 220]
  [197 211 219]
  [199 214 221]]

 [[154 155 121]
  [148 149 115]
  [146 149 117]
  ...
  [198 212 220]
  [198 212 220]
  [199 214 221]]

 [[165 165 133]
  [152 152 120]
  [155 156 124]
  ...
  [201 215 223]
  [199 214 221]
  [199 214 221]]

 ...

 [[113 116 104]
  [ 87  90  78]
  [ 81  83  67]
  ...
  [ 47  69  79]
  [ 49  69  79]
  [ 46  67  76]]

 [[108 109  93]
  [ 75  77  61]
  [ 73  73  53]
  ...
  [ 42  65  72]
  [ 44  65  72]
  [ 43  64  71]]

 [[ 99  98  80]
  [ 75  75  57]
  [ 70  69  46]
  ...
  [ 43  64  71]
  [ 43  64  71]
  [ 38  59  67]]]
[[[122 119  99]
  [141 139 119]
  [160 158 136]
  ...
  [189 205 217]
  [189 205 217]
  [201 216 228]]

 [[145 145 125]
  [156 156 135]
  [158 158 138]
  ...
  [199 216 228]
  [195 210 223]
  [202 217 230]]

 [[171 174 149]
  [164 167 142]
  [159 162 139]
  ...
  [199 216 228]
  [196 214 226]
  [198 215 227]]

 ...

 [[120 127 108]
  [ 97 103  85]
  [ 64  62  33]
  ..

  [ 66  73  59]]]
[[[138 142 115]
  [150 154 126]
  [164 173 145]
  ...
  [208 225 230]
  [206 225 230]
  [201 220 225]]

 [[148 154 126]
  [149 155 127]
  [153 159 131]
  ...
  [205 222 228]
  [210 227 232]
  [203 220 225]]

 [[164 170 143]
  [156 162 134]
  [148 157 129]
  ...
  [188 204 212]
  [195 214 220]
  [192 211 216]]

 ...

 [[ 74  74  81]
  [124 124 131]
  [116 122 113]
  ...
  [ 71  78  68]
  [ 67  73  66]
  [ 70  77  69]]

 [[107 109 113]
  [120 121 126]
  [111 116 104]
  ...
  [ 66  72  64]
  [ 67  72  67]
  [ 68  74  69]]

 [[105 107 109]
  [108 110 112]
  [108 113 102]
  ...
  [ 62  68  61]
  [ 67  72  67]
  [ 68  74  69]]]
[[[146 149 133]
  [148 152 135]
  [149 156 137]
  ...
  [190 200 206]
  [205 214 223]
  [209 219 227]]

 [[152 154 138]
  [151 152 136]
  [141 148 129]
  ...
  [200 212 220]
  [210 224 232]
  [208 222 230]]

 [[159 158 142]
  [167 166 150]
  [153 157 136]
  ...
  [206 221 228]
  [208 222 230]
  [209 223 231]]

 ...

 [[ 93  94  91]
  [120 120 118]
  

<function destroyAllWindows>